### ISSUE TITLE
build does not work due to jsondoc

### ISSUE THREAD

**Issue by MariusKl** [HelfenKannJeder/come2help-server#26] opened 2015-11-30 19:45 UTC
in branch feature_oauth2

**Comment by andreas-eberle** [comment] 2015-12-02 10:56
It seems that jsondoc has a problem with the OAuth2ClientController class. There are also bean definitions and and @Configuration annotation in this class. Maybe this is something jsondoc can't handle. 

If I move the OAuth2ClientController class to the configuration package, it works again. But I guess this is only because jsondoc does not scan this folder.

**Comment by andreas-eberle** [comment] 2015-12-04 17:25
I moved the configuration part back to the configuration package. That fixed it for now. So when you want to reproduce it, you need to use an older state of the branch.

As it is "fixed" for me atm, I'm closing this.

**Closed by andreas-eberle** 2015-12-04 17:25 UTC
Labels: bug

**Comment by MariusKl** [comment] 2015-12-04 17:56
Thanks! I already had a look on Wednesday but did not find the problem. Wanted to continue today but thanks to you I can do something else ;)
